$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        1000:{
            items:5
        }
    }
})